<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net6.0;net8.0</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<!-- 允许不安全代码 -->
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<!-- 生成文档文件 -->
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
	</PropertyGroup>

</Project>
